image: node

before_script:
  - echo $ENVTS > server/src/env.ts

stages:
  - build
  - test
  - lint

build-client:
  stage: build
  script:
    - cd client
    - yarn install
    - yarn build
  artifacts:
    paths:
      - server/client

build-server:
  stage: build
  script:
    - cd server
    - yarn install
    - yarn build
    - mv dist public
  artifacts:
    paths:
      - server/public

test-server:
  stage: test
  script:
    - cd server
    - yarn install
    - yarn test

lint-client:
  stage: lint
  script:
    - cd client
    - yarn install
    - yarn lint --no-fix

lint-server:
  stage: lint
  script:
    - cd server
    - yarn install
    - yarn lint:check
    - yarn format:check
